### ISSUE TITLE
objectIdTranslate

### ISSUE THREAD

**Issue by KonstantinGa** [Rudy-Tmc/backupAndRestoreInsightCloud#1]
Hi, 
i face an issue in restoring (it resored ~40% of object):  
and stopped on: 

2022-06-20 12:48:56,551 root         INFO     [71] Creating object: Server 99 [Servers]
2022-06-20 12:49:03,799 root         ERROR    [592] Unhandled error
'id'
Traceback (most recent call last):
  File "C:\...\importObjectSchema.py", line 414, in <module>
    objectIdTranslate[oldObject['id']]=newObject['id']
KeyError: 'id'
2022-06-20 12:49:03,799 root         INFO     [595] ------------End of Run------------
Traceback (most recent call last):
  File "C:\temp\backup\backup\importObjectSchema.py", line 414, in <module>
    objectIdTranslate[oldObject['id']]=newObject['id']
KeyError: 'id'

**Comment by Rudy-Tmc** [comment]
Hi Konstatin,

It looks like the object was not created. I've updated the script to give better output and it should not fail anymore with the keyError. If you want more info, you should run the script in debug mode. You can change the logging level in line 17 (fileLogger.setLevel(logging.INFO ==> fileLogger.setLevel(logging.DEBUG). This will send more info to the import.log file. Which gives me better analysing options.

Rudy

**Comment by KonstantinGa** [comment]
Thank you, Rudy
Looks like it fails on Special characters (We use Baltic letters)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\encodings\cp1257.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xc1' in position 194: character maps to <undefined>
Call stack:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\importObjectSchema.py", line 45, in updateObjectByObjectTypeId
    updatedObject = myInsight.updateObjectByObjectTypeId(updateObjectId, updateObjectTypeId, objectData)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\insight.py", line 404, in updateObjectByObjectTypeId
    return self.updateObject(objectId,json.loads(payload))
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\insight.py", line 377, in updateObject
    logging.debug("updateObject id:"+str(objectId)+", data:"+(str(data)))
Message: "updateObject id:100871, data:{'objectTypeId': '779', 'attributes': [{'objectTypeAttributeId': '2429', 'objectAttributeValues': [{'value': 'Pr.Ár.Acrobat standard DC 2015 1 user'}]}, {'objectTypeAttributeId': '2379', 'objectAttributeValues': [{'value': '0.29'}]}, {'objectTypeAttributeId': '2329', 'objectAttributeValues': [{'value': '2022-06-08T09:45:00.000+03:00'}]}, {'objectTypeAttributeId': '2327', 'objectAttributeValues': [{'value': 'FTIR-73063'}]}, {'objectTypeAttributeId': '2392', 'objectAttributeValues': [{'value': 'RES2-101615'}]}, {'objectTypeAttributeId': '2328', 'objectAttributeValues': [{'value': 'Adobe On Premise 50'}]}, {'objectTypeAttributeId': '2382', 'objectAttributeValues': [{'value': 'PRG0029'}]}, {'objectTypeAttributeId': '2395', 'objectAttributeValues': [{'value': 'On Premise license'}]}, {'objectTypeAttributeId': '2383', 'objectAttributeValues': [{'value': 'RES2-106786'}]}, {'objectTypeAttributeId': '2393', 'objectAttributeValues': [{'value': 'RES2-104078'}]}, {'objectTypeAttributeId': '2430', 'objectAttributeValues': [{'value': 'GA_ADM_IT'}]}, {'objectTypeAttributeId': '2378', 'objectAttributeValues': [{'value': '2016-12-15'}]}, {'objectTypeAttributeId': '2330', 'objectAttributeValues': [{'value': '2022-06-08T09:45:00.000+03:00'}]}]}"
Arguments: ()

**Comment by KonstantinGa** [comment]
And one more
File "C:\Users\konstantin.gagac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
2022-06-20 16:02:34,675 root         ERROR    [596] Unhandled error
'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\importObjectSchema.py", line 436, in <module>
    newObject = future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\importObjectSchema.py", line 45, in updateObjectByObjectTypeId
    updatedObject = myInsight.updateObjectByObjectTypeId(updateObjectId, updateObjectTypeId, objectData)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\insight.py", line 403, in updateObjectByObjectTypeId
    payload = self.constructObjectPayload(myDict,objectTypeId)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\insight.py", line 658, in constructObjectPayload
    attribute = self.getAttributeByName(objectTypeId,key, True)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\insight.py", line 606, in getAttributeByName
    for attribute in attributes:
TypeError: 'NoneType' object is not iterable
2022-06-20 16:02:34,678 root         INFO     [599] ------------End of Run------------
Traceback (most recent call last):
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\importObjectSchema.py", line 436, in <module>
    newObject = future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\importObjectSchema.py", line 45, in updateObjectByObjectTypeId
    updatedObject = myInsight.updateObjectByObjectTypeId(updateObjectId, updateObjectTypeId, objectData)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\insight.py", line 403, in updateObjectByObjectTypeId
    payload = self.constructObjectPayload(myDict,objectTypeId)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\insight.py", line 658, in constructObjectPayload
    attribute = self.getAttributeByName(objectTypeId,key, True)
  File "C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main\insight.py", line 606, in getAttributeByName
    for attribute in attributes:
TypeError: 'NoneType' object is not iterable
PS C:\temp\backup\fresh\backupAndRestoreInsightCloud-main (1)\backupAndRestoreInsightCloud-main>

**Comment by Rudy-Tmc** [comment]
Yes, But I still am confused where the problem is. Is it on the json.loads(payload) (line 404) or on the logging.debug (line 377)

It fails on line 377:
`logging.debug("updateObject id:"+str(objectId)+", data:"+(str(data)))`
Could you comment it out / delete it and try again?

If it does not work, could you send me the json files of the 'Servers' objects (the object that fails).
I only need the attributes and the object data of 1 object.

**Comment by Rudy-Tmc** [comment]
Hi Konstantin,

I've created an object in Insight starting with Á (https://charbase.com/00c1-unicode-latin-capital-letter-a-with-acute) 
In the objects\<myobject>.json I can see the data as follows:
```
{
  "135961": {
    "Created": "20/Jun/22 2:34 PM",
    "Key": "TST-135961",
    "Name": "\u00c1 - LATIN CAPITAL LETTER A WITH ACUTE",
    "Updated": "20/Jun/22 2:34 PM"
  }
}
```
Do you also have **\u00c1** in your backed up JSON file? or do you see **u'\xc1'** as mentioned in the trace.
My backup and restore with this character in an object attribute works fine.

**Comment by KonstantinGa** [comment]
Hi, yes it's \u00c1 but maybe r is not good
here is part of Json

"objectAttributeValues": [
          {
            "displayValue": "Pr.\u00c1r.Acrobat standard DC 2015 1 user",
            "referencedType": false,
            "searchValue": "Pr.\u00c1r.Acrobat standard DC 2015 1 user",
            "value": "Pr.\u00c1r.Acrobat standard DC 2015 1 user"
          }

**Comment by Rudy-Tmc** [comment]
Hi Konstatin, you showed me a piece of the output. But could you give me the data in the backup file of this object?
It is in <data_time>\<objectschemakey>\objects\<objecttypename>_<objecttypeid>.json.

Is it stored as \uc00c1 or as \xc1?

I've copied the displayValue into mine backup and that just works.

```
  "135961": {
    "Created": "20/Jun/22 2:34 PM",
    "Key": "TST-135961",
    "Name": "Pr.\u00c1r.Acrobat standard DC 2015 1 user",
    "Updated": "20/Jun/22 2:34 PM"
  }
```
![image](https://user-images.githubusercontent.com/12659231/174746539-abbfc412-ee1e-4971-a5ce-88adf4709f34.png)

**Comment by KonstantinGa** [comment]
Hi, Ruby
Thanks for your support and useful tool (at least it let me recreate structure)
Sorry i can't share JSONS. 
But here is feedback: 
it's \u00c1
i replaced it in all file with "i" letter - now process finished with "INFO     [599] ------------End of Run------------"
So this looks like resolved. 

But what i noted: 
My initial Scheme Backup from has 14618 Objects (in ObjectSchema it writes:   "objectCount": 14619)
My Recovered Scheme has only 6448 Objects 

i have doubt that it's not create new object if it has same Name (insight allows create same name Objects)
For example i see Asset is created and there a huge history added on this item (of all same named objects). 
Maybe it could some how resolved? Of let it create as stand alone objects or add some incremental to name in future versions?


There was NO errors in log, 
but there were some warnings like this: 

WARNING  [715] constructObjectPayload > Can't find referenced object Owner for value: SomeOwner
This warning related to Asset that should have SomeOwner referenced on Onwer
On one hand this current SomeOwner has another Assets that was was successfully referenced.
On other hand same ObjectType Assets referenced with other Owners without any issues.

**Comment by Rudy-Tmc** [comment]
> i have doubt that it's not create new object if it has same Name (insight allows create same name Objects)
That is indeed still a limitation. Could you explain to me why you want to have objects with the same label but with different purpose? I know it is possible, but should it be?

E.g. what's the point of having an object 'Laptop' where you have 100 objects called 'MacBook'? As a user I can't distinguish properly between them. So do you have a reason of having objects with the same name?

Note that does not make it right that the script does not import all objects. I just wanted to know if there is a rational to do this.
I will try to fix it. It will take me a bit of time to simulate the behaviour and fix it.

The other issue is odd and should not happen if similar objects have correct references reconstructed. The only time I've seen it, was when I had the threads set to a larger number. I will add a script to the repo which you can use to update the contents of one object_id.json file. Which should fix this warning for you.

**Comment by Rudy-Tmc** [comment]
I've updated the scripts. It now will create similar named/labeled objects. Also referenced objects implementation has changed. Due to this you need to redo a backup and use that to import it.
A object id translation file will be generated in the <date-time>\ location, called createdObjects.json.
During a second run (if the first one is aborted) it will use this to identify already created objects.
